// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hauouywirzweejvzfmpo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhdW91eXdpcnp3ZWVqdnpmbXBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMjEyMDIsImV4cCI6MjA3MDU5NzIwMn0.emTHT2hTqJyYb_kkJOdVqArLDbCXqFcUZ9VeJUjiyew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});